clusters:
  cluster1:
    prometheus: "https://prometheus.hetzner.lab.flanksource.com"
    alertmanager: "https://alertmanager.hetzner.lab.flanksource.com"
    canaryChecker: "https://canaries.hetzner.lab.flanksource.com/api"
    kubeconfig: "kubeconfig.yml"

  cluster2:
    prometheus: "https://prometheus.hetzner.lab.flanksource.com"
    alertmanager: "https://alertmanager.hetzner.lab.flanksource.com"
    canaryChecker: "https://canaries.hetzner.lab.flanksource.com/api"
    kubeconfig: "kubeconfig.yml"