name: Create Docker
on:
  push:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    container: 
      image: node
    steps:
    - uses: actions/checkout@master
    - name: Installing dependencies
      run: npm install
    - name: Build project
      run: npm run build
    
  cd:
    runs-on: ubuntu-latest
    needs: ci
    
    steps:
      - name: Checkout code
      - uses: actions/checkout@master
        
      - name: Build and push Docker images
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: simbatsuro/karina
          tags: latest          
          
